### ISSUE TITLE
yarn start失败：digital envelope routines::unsupported

### ISSUE THREAD

**Issue by wencan** [NetEase/tango#40]
os: fedora 38
kernel: 6.5.5-200.fc38.x86_64
node: v18.18.0
code commit: 1a17ee1e94825b983bfa52d275b1106aefc61ed2  

```
$ yarn start
yarn run v1.22.19
$ yarn workspace playground start
$ umi dev
Starting the development server...

● Webpack █████████████████████████ building (10%) 1/2 modules 1 active
 babel-loader › src/.umi/umi.ts

(node:48865) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node-18 --trace-deprecation ...` to show where the warning was created)
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports.__webpack_modules__.57442.module.exports (/home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:135907:62)
    at NormalModule._initBuildHash (/home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109317:16)
    at /home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109352:10
    at /home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:109223:13
    at /home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61151:11
    at /home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:61017:18
    at context.callback (/home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/webpack/4/bundle4.js:60895:13)
    at /home/wencan/Projects/github.com/NetEase/tango/node_modules/@umijs/deps/compiled/babel-loader/index.js:1:130029 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.18.0
Done in 2.85s.
```

**Comment by ccloli** [comment]
See https://github.com/NetEase/tango/issues/14#issuecomment-1707550792 .

请尝试使用如下指令启动：
```sh
NODE_OPTIONS="--openssl-legacy-provider" yarn start
```
或者降级至 Node 16
